In [ ]:
import numpy as np
a = [[1,2,3],[2,3,4],[2,5,6]]
vec = np.array(a)
print(vec)
print("\n type of vec is:")
print(type(vec))
print(vec.shape)
print(vec.dtype)
print(vec[0])
print(vec[0][0])
print(vec[1])
print(vec[2])

In [ ]:
import numpy as np
a = np.array([[[1],[2],[3]],[[2],[3],[4]],[[2],[5],[6]]])
print(a)
print(a.shape)
print(a.dtype)


## Array functions

- RESHAPE  (output will always be 2-D array)

In [ ]:
list1= [1,2,3,4,5,6,7,8,9,10]
a= np.array(list1)
print(a)
print(a.shape)
b=print(a.reshape(5,2))

print(a.reshape(-1,1))

- Ravel() => used to convert any dimentional array to 1-D array.

In [ ]:
a = np.array([[[1],[2],[3]],[[2],[3],[4]],[[2],[5],[6]]])
print(a)
print(a.shape)
b= a.ravel()
print(b)
print(b.shape)

- tolist() => get back to original array...possible in tuples

In [ ]:
list1= [1,2,3,4,5,6,7,8,9,10]
a= np.array(list1)
print(a)
print(a.tolist())

## Data type conversion

In [ ]:
a= [1,2,2]
ar= np.array(a, dtype= float)
print(ar)
print(type(ar))
print(ar.dtype)


a= [1.2,2.2,2.2]
ar= np.array(a, dtype=int)
print(ar)
print(type(ar))
print(ar.dtype)

## frequently used arrays

- Zeros()  => convert all arrays into zeroes

In [ ]:
a= np.zeros((2,3))
print(a)

a= np.zeros((100,100),dtype= int)
print(a)

- ones() => create arrays with values of 1

In [ ]:
a= np.ones((2,3))
print(a)

a= np.ones((100,100),dtype= int)
print(a)

- full() => fill matrix with desired value

In [ ]:
a= np.full(shape=(2,3),fill_value=4)
print(a)

a= np.full(shape = (10,10),fill_value=4,dtype= int)
print(a)

- eye() => gives identity matrices (diagonal values)
- k = 0 (default value) -> can takes negative value.. used for shit of identiy values in matrix

In [ ]:
a= np.eye(3,3,k=0)
print(a)

a= np.eye(10,10,k=0,dtype= int)
print(a)

- random.random() => gives create a random matrix and gives random values to matrix in every execution.

In [ ]:
a= np.random.random((3,3))
print(a)

In [ ]:
a= np.random.randint(1,10,size=(3,3))
print(a)

##  Array slicing 

In [20]:
import numpy as np
ar = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a= np.array(ar)
print(a[0:2,0:3])
print(a[0:1,0:3])
print(a[0:3:2,0:3:2])
print(a[::2,1::2])
print(a[:-1,::3])
b= a[::2, 1::2]
print(b)

b[1,0] = 99
print(b)
print(a)

[[1 2 3]
 [5 6 7]]
[[1 2 3]]
[[ 1  3]
 [ 9 11]]
[[ 2  4]
 [10 12]]
[[1 4]
 [5 8]]
[[ 2  4]
 [10 12]]
[[ 2  4]
 [99 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 99 11 12]]


In [21]:
print(a[:-1,[0,2,3]])  #selctive slicing

[[1 3 4]
 [5 7 8]]


In [22]:
b= a%2==0
print(b)
c= a[b]
print(c)

[[False  True False  True]
 [False  True False  True]
 [False False False  True]]
[ 2  4  6  8 12]


## Array operations (mathematical)

In [23]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
print(a)
print(b)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [24]:
print(a+b)
print(np.add(a,b))  #addition

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [25]:
print(a-b)
print(np.subract(a,b))  #subraction

[[-4 -4]
 [-4 -4]]


AttributeError: module 'numpy' has no attribute 'subract'

In [26]:
print(a.dot(b))

[[19 22]
 [43 50]]


In [27]:
a= np.arange(1,10,0.5)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [28]:
a= np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
